services:

  frontend:
    build:
      context: ./front-end
    ports:
      - "8080:8080"  # React dev server
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - flask-app
    command: npm run dev
    networks:
      - my-network

  flask-app:
    build: ./back-end
    ports:
      - "5000:5000"  # Expose port 5000
    volumes:
      - ./back-end:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development  # Enable Flask's auto-reloading
    command: python3 -m flask run --debug
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
