services:

  frontend:
    build:
      context: ./front-end
    ports:
      - "8080:8080"  # React dev server
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - flask-app
    networks:
      - my-network

  flask-app:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development  # Enable Flask's auto-reloading  
    depends_on:
      - db  
    networks:
      - my-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: binhunter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: