"""Auto migration

Revision ID: c0a3e22ac982
Revises: 
Create Date: 2024-10-20 13:18:04.777156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a3e22ac982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmwares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firmware_name', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firmware_name'),
    sa.UniqueConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firmwares')
    # ### end Alembic commands ###
